- name: Update repoistory index (Ubuntu)
  tags: always
  apt:
    update_cache: yes
    force_apt_get: yes
  when: ansible_distibution == "Ubuntu"

- name: Upgrade apt packages (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    force_apt_get: yes
  when: ansible_distibution == "Ubuntu"